---
- name: Install and start apache
  hosts: openshift-cnv-test
  #become: yes

  tasks:
    - name: Install apache
      dnf:
        name: httpd
        state: present

    - name: Permit traffic in default zone for http service
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true
      check_mode: false

    - name: Start apache
      service:
        name: httpd
        state: started
      check_mode: false
