- name: Create VMs
  connection: local
  gather_facts: false
  hosts: localhost
  tasks:
    - name: Create or terminate a VirtualMachine
      kubevirt.core.kubevirt_vm:
        state: running
        name: test
        namespace: kubevirt
        wait: yes
        wait_timeout: 600
        spec:
          nodeSelector:
            nested: "true"
          domain:
            cpu:
              sockets: 1
            memory:
              guest: 1536Mi
            devices:
              interfaces:
                - name: default
                  masquerade: {}
                - name: bridge-network
                  bridge: {}
          networks:
            - name: default
              pod: {}
            - name: bridge-network
              multus:
                networkName: kindexgw
          volumes:
            - containerDisk:
                image: quay.io/containerdisks/fedora:latest
              name: containerdisk
            - cloudInitNoCloud:
                userData: |-
                  #cloud-config
                  ssh_authorized_keys:
                    - {{ lookup('file', 'pub_key') }}
              name: cloudinit
