- hosts: localhost
  connection: local
  tasks:
  - name: Create a VirtualMachine with a DataVolume template
    kubevirt.core.kubevirt_vm:
      state: present
      name: testvm-with-dv
      namespace: default
      labels:
        app: student
      instancetype:
        name: u1.medium
      preference:
        name: fedora
      data_volume_templates:
        - metadata:
            name: testdv
          spec:
            source:
              registry:
                url: docker://quay.io/containerdisks/fedora:latest
            storage:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 5Gi
